import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('data/my_subscriptions.csv')
print("First look at my subscription data: ")
print(df.head())
print("\n")
print("Info about the data:")
print(df.info())
print(f"Total number of subscriptions: {len(df)}")
total_monthly_cost = df['monthly_cost'].sum()
print(f"Total monthly cost: ${total_monthly_cost:.2f}")
average_cost = df['monthly_cost'].mean()
print(f"Average cost per subscription: ${average_cost:.2f}")
spending_by_category = df.groupby('category')['monthly_cost'].sum()
print("\nSpending by Category:")
print(spending_by_category)
plt.figure(figsize=(8,8))
plt.pie(spending_by_category, labels=spending_by_category.index, autopct='%1.1f%%')
plt.title('Monthly Spending by Category')
plt.savefig('spending_pie_chart.png')
print("Pie chart saved as 'spending_pie_chart.png'")
plt.figure(figsize=(10, 6))
plt.bar(spending_by_category.index, spending_by_category.values)
plt.title('Monthly Spending by Category')
plt.xlabel('Category')
plt.ylabel('Monthly Cost ($)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('spending_bar_chart.png')
print("Bar chart saved as 'spending_bar_chart.png'")